theme = "webstack"
version = "20.06.09"

# 首页网址
baseURL = "https://nav.game2d.com"
# 标题
title = "游戏开发大全导航"

beian = "鄂ICP备19021662号-2"

[params]
    # 副标题
    subtitle = "游戏开发资源大全，包含各种工具、知名博客、免费资源、开源项目"
    # css和js文件的cdn
    cdn = "https://cdn.jsdelivr.net/gh/weibobo/nav-game2d-static/theme"
    # 开启今日诗词
    jinrishici = "true"
    # 开启访问量统计
    busuanzi = "false"
